POST https://node-do-zero-jd6n.onrender.com/videos
Content-type: application/json

{
    "title": "Video Node",
    "description": "Esse é o primeiro video",
    "duration": 180
}

###

GET https://node-do-zero-jd6n.onrender.com/videos

###

PUT https://node-do-zero-jd6n.onrender.com/videos/ff2d61ff-4877-40dc-b92b-c888aa39a4ce
Content-type: application/json

{
    "title": "Video 02",
    "description": "Esse é o primeiro video",
    "duration": 180
}

###

DELETE https://node-do-zero-jd6n.onrender.com/videos/ff2d61ff-4877-40dc-b92b-c888aa39a4ce