POST http://localhost:3333/videos
Content-type: application/json

{
    "title": "Video Node",
    "description": "Esse é o primeiro video",
    "duration": 180
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/e9d1909f-44d1-4804-a885-a46a8e5f9e6a
Content-type: application/json

{
    "title": "Video 02",
    "description": "Esse é o primeiro video",
    "duration": 180
}

###

DELETE http://localhost:3333/videos/e9d1909f-44d1-4804-a885-a46a8e5f9e6a